name: CI tests

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions:
          - node: '17.x'
          - node: '16.x'
          - node: '15.x'
          - node: '14.x'
          - node: '13.x'
          - node: '12.x'
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.versions.node }}
      - run: npm install
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
